[package]
name = "pyrustml"
version = "0.2.0"
edition = "2021"
description = "High-performance ML algorithms in Rust with Python bindings"
license = "MIT"
authors = ["PyRust-ML Team"]

[lib]
name = "pyrustml"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"] }
numpy = "0.20"
ndarray = { version = "0.15", features = ["rayon"] }
rayon = "1.8"
rand = "0.8"
nalgebra = "0.32"
approx = "0.5"
thiserror = "1.0"

[build-dependencies]
pyo3-build-config = "0.20"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1